//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import { type ModelResult as $ModelResult } from "@zenstackhq/runtime";
export type User = $ModelResult<$Schema, "User">;
export type Content = $ModelResult<$Schema, "Content">;
export type Post = $ModelResult<$Schema, "Post">;
export type Image = $ModelResult<$Schema, "Image">;
export type Video = $ModelResult<$Schema, "Video">;
