//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, type AttributeApplication, type FieldDefault, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "sqlite"
    } as const;
    models = {
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("autoincrement") as FieldDefault
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                contents: {
                    name: "contents",
                    type: "Content",
                    array: true,
                    relation: { opposite: "owner" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                email: { type: "String" }
            }
        },
        Content: {
            name: "Content",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("autoincrement") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                owner: {
                    name: "owner",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("Int", [ExpressionUtils.field("ownerId")]) }, { name: "references", value: ExpressionUtils.array("Int", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
                    relation: { opposite: "contents", fields: ["ownerId"], references: ["id"] }
                },
                ownerId: {
                    name: "ownerId",
                    type: "Int",
                    foreignKeyFor: [
                        "owner"
                    ] as readonly string[]
                },
                viewCount: {
                    name: "viewCount",
                    type: "Int",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }] as readonly AttributeApplication[],
                    default: 0 as FieldDefault
                },
                type: {
                    name: "type",
                    type: "String",
                    isDiscriminator: true
                }
            },
            attributes: [
                { name: "@@delegate", args: [{ name: "discriminator", value: ExpressionUtils.field("type") }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            },
            isDelegate: true,
            subModels: ["Post", "Image", "Video"]
        },
        Post: {
            name: "Post",
            baseModel: "Content",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("autoincrement") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String",
                    originModel: "Content"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    originModel: "Content",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                owner: {
                    name: "owner",
                    type: "User",
                    originModel: "Content",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("Int", [ExpressionUtils.field("ownerId")]) }, { name: "references", value: ExpressionUtils.array("Int", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
                    relation: { opposite: "contents", fields: ["ownerId"], references: ["id"] }
                },
                ownerId: {
                    name: "ownerId",
                    type: "Int",
                    originModel: "Content",
                    foreignKeyFor: [
                        "owner"
                    ] as readonly string[]
                },
                viewCount: {
                    name: "viewCount",
                    type: "Int",
                    originModel: "Content",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }] as readonly AttributeApplication[],
                    default: 0 as FieldDefault
                },
                type: {
                    name: "type",
                    type: "String",
                    originModel: "Content",
                    isDiscriminator: true
                },
                content: {
                    name: "content",
                    type: "String"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        },
        Image: {
            name: "Image",
            baseModel: "Content",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("autoincrement") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String",
                    originModel: "Content"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    originModel: "Content",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                owner: {
                    name: "owner",
                    type: "User",
                    originModel: "Content",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("Int", [ExpressionUtils.field("ownerId")]) }, { name: "references", value: ExpressionUtils.array("Int", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
                    relation: { opposite: "contents", fields: ["ownerId"], references: ["id"] }
                },
                ownerId: {
                    name: "ownerId",
                    type: "Int",
                    originModel: "Content",
                    foreignKeyFor: [
                        "owner"
                    ] as readonly string[]
                },
                viewCount: {
                    name: "viewCount",
                    type: "Int",
                    originModel: "Content",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }] as readonly AttributeApplication[],
                    default: 0 as FieldDefault
                },
                type: {
                    name: "type",
                    type: "String",
                    originModel: "Content",
                    isDiscriminator: true
                },
                data: {
                    name: "data",
                    type: "Bytes"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        },
        Video: {
            name: "Video",
            baseModel: "Content",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("autoincrement") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String",
                    originModel: "Content"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    originModel: "Content",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                owner: {
                    name: "owner",
                    type: "User",
                    originModel: "Content",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("Int", [ExpressionUtils.field("ownerId")]) }, { name: "references", value: ExpressionUtils.array("Int", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
                    relation: { opposite: "contents", fields: ["ownerId"], references: ["id"] }
                },
                ownerId: {
                    name: "ownerId",
                    type: "Int",
                    originModel: "Content",
                    foreignKeyFor: [
                        "owner"
                    ] as readonly string[]
                },
                viewCount: {
                    name: "viewCount",
                    type: "Int",
                    originModel: "Content",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }] as readonly AttributeApplication[],
                    default: 0 as FieldDefault
                },
                type: {
                    name: "type",
                    type: "String",
                    originModel: "Content",
                    isDiscriminator: true
                },
                url: {
                    name: "url",
                    type: "String"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        }
    } as const;
    authType = "User" as const;
    plugins = {};
}
export const schema = new SchemaType();
