//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
const _schema = {
    provider: {
        type: "sqlite"
    },
    models: {
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }]
                },
                contents: {
                    name: "contents",
                    type: "Content",
                    array: true,
                    relation: { opposite: "owner" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                email: { type: "String" }
            }
        },
        Content: {
            name: "Content",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                name: {
                    name: "name",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                owner: {
                    name: "owner",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("ownerId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }] }],
                    relation: { opposite: "contents", fields: ["ownerId"], references: ["id"] }
                },
                ownerId: {
                    name: "ownerId",
                    type: "Int",
                    foreignKeyFor: [
                        "owner"
                    ]
                },
                viewCount: {
                    name: "viewCount",
                    type: "Int",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }],
                    default: 0
                },
                type: {
                    name: "type",
                    type: "String",
                    isDiscriminator: true
                }
            },
            attributes: [
                { name: "@@delegate", args: [{ name: "discriminator", value: ExpressionUtils.field("type") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            },
            isDelegate: true,
            subModels: ["Post", "Image", "Video"]
        },
        Post: {
            name: "Post",
            baseModel: "Content",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                name: {
                    name: "name",
                    type: "String",
                    originModel: "Content"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    originModel: "Content",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                owner: {
                    name: "owner",
                    type: "User",
                    originModel: "Content",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("ownerId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }] }],
                    relation: { opposite: "contents", fields: ["ownerId"], references: ["id"] }
                },
                ownerId: {
                    name: "ownerId",
                    type: "Int",
                    originModel: "Content",
                    foreignKeyFor: [
                        "owner"
                    ]
                },
                viewCount: {
                    name: "viewCount",
                    type: "Int",
                    originModel: "Content",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }],
                    default: 0
                },
                type: {
                    name: "type",
                    type: "String",
                    originModel: "Content",
                    isDiscriminator: true
                },
                content: {
                    name: "content",
                    type: "String"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        },
        Image: {
            name: "Image",
            baseModel: "Content",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                name: {
                    name: "name",
                    type: "String",
                    originModel: "Content"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    originModel: "Content",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                owner: {
                    name: "owner",
                    type: "User",
                    originModel: "Content",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("ownerId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }] }],
                    relation: { opposite: "contents", fields: ["ownerId"], references: ["id"] }
                },
                ownerId: {
                    name: "ownerId",
                    type: "Int",
                    originModel: "Content",
                    foreignKeyFor: [
                        "owner"
                    ]
                },
                viewCount: {
                    name: "viewCount",
                    type: "Int",
                    originModel: "Content",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }],
                    default: 0
                },
                type: {
                    name: "type",
                    type: "String",
                    originModel: "Content",
                    isDiscriminator: true
                },
                data: {
                    name: "data",
                    type: "Bytes"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        },
        Video: {
            name: "Video",
            baseModel: "Content",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                name: {
                    name: "name",
                    type: "String",
                    originModel: "Content"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    originModel: "Content",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                owner: {
                    name: "owner",
                    type: "User",
                    originModel: "Content",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("ownerId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }] }],
                    relation: { opposite: "contents", fields: ["ownerId"], references: ["id"] }
                },
                ownerId: {
                    name: "ownerId",
                    type: "Int",
                    originModel: "Content",
                    foreignKeyFor: [
                        "owner"
                    ]
                },
                viewCount: {
                    name: "viewCount",
                    type: "Int",
                    originModel: "Content",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }],
                    default: 0
                },
                type: {
                    name: "type",
                    type: "String",
                    originModel: "Content",
                    isDiscriminator: true
                },
                url: {
                    name: "url",
                    type: "String"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        }
    },
    authType: "User",
    plugins: {}
} as const satisfies SchemaDef;
type Schema = typeof _schema & {
    __brand?: "schema";
};
export const schema: Schema = _schema;
export type SchemaType = Schema;
